name: nasa project ci
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use NodeJS version 16.16.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.16.0
      - run: npm install
      - run: npm run build --prefix client
